M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu24.04.1} date 2026-04-12T15:29:52+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-12T15:29:52+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.100
%
G90
G05
T1
X29.52Y-19.61
X29.52Y-25.39
T2
X1.8Y-1.6
X1.8Y-32.1
X32.3Y-1.6
X32.3Y-32.1
M30
