M48
; DRILL file {KiCad 9.0.6} date 2026-02-21T19:38:50+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-21T19:38:50+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.100
%
G90
G05
T1
X27.42Y-18.69
X27.42Y-24.47
T2
X1.75Y-1.75
X1.75Y-32.25
X32.25Y-1.75
X32.25Y-32.25
M30
